---
title: "Licht-sediment relatie in de Schelde"
output: html_notebook
---

```{r setup}
require(tidyverse)
require(skimr)
require(leaflet)
```

```{r loadData}
load(file = "ScheldeSlib.Rdata")
# geladen als df_wide
```


```{r}
df_wide %>% 
  gather("variable", "value", -latitude, -longitude, -depth, -datetime, -stationname, -dataprovider, -watersysteem, -Omessegmen) %>%
  filter(variable != "E_/m" | value < 20) %>% 
  filter(variable != "SPM_mg/l" | value < 500) %>% 
  ggplot(aes(x = value)) +
  geom_histogram(aes(fill = dataprovider)) +
  facet_wrap(~ variable, scales = "free") +
  scale_x_log10() +
  theme(legend.position = "bottom")
```

```{r}
df_wide %>% 
  gather("variable", "value", -latitude, -longitude, -depth, -datetime, -stationname, -dataprovider, -watersysteem, -Omessegmen) %>%
  filter(variable != "E_/m" | value < 20) %>% 
  filter(variable != "SPM_mg/l" | value < 500) %>% 
  ggplot(aes(x = value)) +
  geom_histogram(aes(fill = watersysteem)) +
  facet_wrap(~ variable, scales = "free") +
  scale_x_log10() +
  theme(legend.position = "bottom")
```


```{r}
df_wide %>%
  filter(watersysteem == "Schelde") %>%
ggplot(aes(`SPM_mg/l`, `E_/m`)) +
  geom_point(aes(color = lubridate::year(datetime)), size = 1) +
  geom_smooth(method = "lm") +
  scale_x_log10() + scale_y_log10() +
  coord_cartesian(xlim = c(5,500), ylim = c(0.5, 12))
```

```{r}
# `SPM_mg/l`, `E_/m`
fit <- lm(`E_/m` ~ `SPM_mg/l` - 1, data = df)
ggplot(data = df, aes(x = `SPM_mg/l`, y = `E_/m`, label=`E_/m`)) +
  stat_function(fun = function(x) predict(fit, newdata = data.frame(x = x)),
                color = "blue", size = 1.5) +
  annotate(label = sprintf("y = %.3f x\nR² = %.2f", coef(fit), summary(fit)$r.squared),
           geom = "text", x = 25, y = 400, size = 12) +
  geom_point()
```




